import 'dotenv/config';

export const ENV = {
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  COINMARKETCAP_LASTEST_LISTINGS_URL:
    process.env.COINMARKETCAP_LASTEST_LISTINGS_URL,
  COINMARKETCAP_API_KEY: process.env.COINMARKETCAP_API_KEY,
};
